[pytest]
asyncio_mode = auto
testpaths = tests
norecursedirs = .git
markers =
    allow_sockets: Allow network sockets for tests
filterwarnings =
    ignore::pytest_socket.SocketConnectBlockedError
    ignore:A test tried to use socket.socket.connect():UserWarning
    ignore:Skipping live test:UserWarning

