name: Report an issue
description: Report an issue with the db-infoscreen Integration
title: "[Bug]: "
labels: ["bug"]
assignees:
  - FaserF
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        If you have a feature or enhancement request, please use the feature request template!
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here.
        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core has the issue?
      placeholder: core-
      description: >
        Can be found in: [Settings -> About](https://my.home-assistant.io/redirect/info/).

        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        Can be found in: [Settings -> About](https://my.home-assistant.io/redirect/info/).

        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: input
    id: version_integration
    validations:
      required: true
    attributes:
      label: What version of this Integration has the issue?
      placeholder: 
      description: >
        The version from the release page you are using. Latest version can be found here: https://github.com/FaserF/ha-db_infoscreen/releases/latest
  - type: input
    id: station_name
    validations:
      required: false
    attributes:
      label: If possible, please provide the station name you were using.
      placeholder: 
      description: >
        If you dont want to share this due to data privacy, please leave this field empty. You can also provide another station name where you can reproduce the issue.
  - type: dropdown
    id: data_source
    validations:
      required: true
    attributes:
      label: What data source are you using (usually IRIS-TTS)?
      description: >
        Please provide the data source you are using. Initially you had to choose one in the config flow data_source while setting up the integration.
      options:
        - IRIS-TTS  
        - hafas=1  
        - MVV  
        - ÖBB  
        - BSVG  
        - DING  
        - KVV  
        - LinzAG  
        - NVBW  
        - NWL  
        - VGN  
        - VMV  
        - VRN  
        - VRR  
        - VRR2  
        - VRR3  
        - VVO  
        - VVS  
        - bwegt  
        - AVV  
        - BART  
        - BLS  
        - BVG  
        - CMTA  
        - DSB  
        - IE  
        - KVB  
        - NAHSH  
        - NASA  
        - NVV  
        - RMV  
        - RSAG  
        - Resrobot  
        - STV  
        - SaarVV  
        - TPG  
        - VBB  
        - VBN  
        - VMT  
        - VOS  
        - ZVV  
        - mobiliteit
        - Other
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Example YAML snippet
      description: |
        If applicable, please provide an example piece of YAML that can help reproduce this problem.
        This can be from an automation, script, scene or configuration.
      render: yaml
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.